/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Product } from './models/product';
export type { ProductCreateDto } from './models/product-create-dto';
export type { ProductUpdateDto } from './models/product-update-dto';
