/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {
  active?: boolean;
  createdAt?: string;
  createdBy?: string;
  id?: number;
  name?: string;
  price?: number;
  updatedAt?: string;
  updatedBy?: string;
}
