/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductUpdateDto {
  active?: boolean;
  name?: string;
  price?: number;
  updatedAt?: string;
  updatedBy?: string;
}
