/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductCreateDto {
  active?: boolean;
  createdAt?: string;
  createdBy?: string;
  name?: string;
  price?: number;
}
